[fr]
  title = "Tech On Sunday"
  languageName = "Fran√ßais"
  weight = 1
  languagedir = "ltr"
  contentDir = "content/fr" # French

# [en]
#   title = "Tech On Sunday"
#   languageName = "English"
#   weight = 1
#   languagedir = "ltr"
#   contentDir = "content/en" # English
